### ISSUE TITLE
Add a blog to the site

### ISSUE THREAD

**Issue by evanwolf** [openoakland/oak72#5]
the better to share updates in a breaking situation

**Comment by arena** [comment]
oops. didn't mean to close the issue. reopened. 

I was going to comment and say that I think the twitter feeds below the map do this.

**Comment by evanwolf** [comment]
blogs let you explain in more than 140 characters. tweets could drive people to a blog for further explanation. 

oh, and the editorial content of the City's blog is in its custody, in its control, not subject to Twitter's choices about disabling or suspending accounts. 

my 2 cents.
