### ISSUE TITLE
Reduce image megabytes so site loads faster with bad connectivity

### ISSUE THREAD

**Issue by evanwolf** [openoakland/oak72#6]
The site has many images that are large in bytes. We need to offer a site that works when connectivity is impaired or very expensive. So: 
- reduce picture dimensions
- eliminate gratuitous images that don't add value
- optimize (squish) the remaining images
- connect to a CDN (content distribution network)

**Comment by arena** [comment]
The site is set up to use a CDN, it's just in free mode at the moment.

I think all the images add value in the sense that the visual design is complete with them. There are fewer images in the mobile version.

Agree that some images need optimization. Everything is currently a placeholder image.

**Comment by evanwolf** [comment]
Would suggest leaving this issue open until the images are no longer placeholders and we can test the payload effects (load times, navigation, and $$/mbyte) on mobile users.
