### ISSUE TITLE
Suggested additional links for Oak72

### ISSUE THREAD

**Issue by ladyjax** [openoakland/oak72#7]
Add links to : Oakland CORE: http://www2.oaklandnet.com/Government/o/OFD/s/CORE/index.htm
                      Oakland Fire Department: http://www2.oaklandnet.com/Government/o/OFD/index.htm (maybe approach the OFD about a new website of it's own - just a thought. Trying to navigate from the City Website is cumbersome)
Local hospitals: Highland Hospital: http://www.highlandahs.org/
                         Sutter Health Alta Bates Summit Medical Center: http://www.altabatessummit.org/

**Comment by arena** [comment]
added to trello. Good links!
